### PR TITLE
unix: update webserver to Python 3

### PR DESCRIPTION
**Pull request by birkenfeld**
I tested it with and without SSL mode, on Python 3.8, and it looks fine.

I don't know enough about cmake/packaging to adapt these files though.

ref: #305

### CODE REVIEW

**Comment by dcommander** [comment]
Thanks for cluing me in as to how to make the script support Python 3.  I need to do a lot of compatibility testing to determine whether it is necessary to retain support for Python 2, so stand by.

**Comment by birkenfeld** [comment]
In that case, I updated the change to support both.

**Comment by dcommander** [comment]
@birkenfeld Please update the copyright header of the file as well, to reflect that you modified it.  I will merge this along with a commit that changes the Debian package dependencies.

**Comment by birkenfeld** [comment]
Done!

**Pull request closed without merging**
