### PR TITLE
#16 - custom swing component

### PR DESCRIPTION
**Pull request by chaddiller**
This was the easiest way I found to accomplish it without changing too much. The api change is compatible and any existing functionality should work (but didn't test much.)

You construct the VncViewer object with a swing container. This container is used as the parent for the Viewport. Most of the changes are because Viewport no longer extends JFrame.

An issue that isn't resolved is that if the vnc window is bigger than the provided component there is no scroll bar. 

If I make any more updates I'll let you know but I'm not actively looking at it.

### CODE REVIEW

**Comment by dcommander** [comment]
This seems fairly innocuous, and I wouldn't mind checking it in, but I need to get a sense of how generic it is.  Can you show me a simple program that demonstrates embedding the viewer in another component?  Can you also give me more specific information about what your ultimate goal is with this?

**Comment by chaddiller** [comment]
Added EmbeddedVncUsage.java. The ultimate goal is the ability to embed a vnc component into a custom java application. EmbeddedVncUsage demonstrates adding a vnc component to a JFrame with another component.

**Comment by dcommander** [comment]
Can you resubmit these with the proper copyright attributions?  I need to see a new copyright line and (if one doesn't already exist) a license header in all of the files you modified.  I'm assuming that you are making these modifications as an independent agent, on your own time and with your own equipment.  If, however, you are bound by an intellectual property agreement with a particular company or organization, then please contact me offline.

**Comment by dcommander** [comment]
If I don't hear back from you by close of business today, I won't be able to include these patches in TurboVNC 2.1 beta.

**Comment by chaddiller** [comment]
Sorry I don't have time to make any other changes to the source. The current changes are intended to be open source. The changes were made by me, on my own time, with my own equipment. All IP is free from any other agreement or license and should be considered under the same open source license (GPL v2) that this project is under.

**Comment by dcommander** [comment]
OK, that's fine.  Should I attribute it to "Chad Diller"?

**Comment by chaddiller** [comment]
Yes. Thank you.

**Comment by dcommander** [comment]
I spent about 4 hours hacking on this, but unfortunately I ran into some problems trying to integrate the feature into master, and I don't have any more time to look at it right now.  In general, some aspects of the implementation concern me.  I'm not sure if your approach is correct in all cases, since you're bypassing some code that is critical to the proper functioning of the viewer.  From a maintainability point of view, I have to be mindful not to create code paths that will rarely be tested, which means that I would really like to implement this in a manner that re-uses as much of the existing code as possible-- in other words, architecting the solution such that the "normal" operation of the viewer (creating its own JFrame) is a subset of the general case (using any arbitrary JFrame.)  I think such an approach is possible, but it's going to take some significant refactoring in order to make the feature "mostly harmless" from the point of view of the current code base.  It will require some restructuring of the existing classes-- probably moving the JFrame-specific stuff out of Viewport or abstracting it in some other way so that that functionality isn't lost.  I'm leaving this PR open and will revisit in a future release.  Thank you for your contribution.

**Comment by chaddiller** [comment]
Thanks for your assessment. I agree it's not anywhere near production ready. The ideal solution would require a big refactor. Currently there is not enough separation between the socket logic, the swing logic, and the swing application logic.

**Pull request closed without merging**
